/****** Object:  View [gld].[VW_FACT_CONTRACT_STATUS]    Script Date: 9/26/2023 10:43:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [gld].[VW_FACT_CONTRACT_STATUS] AS WITH _SDdata AS (
SELECT
	VBAK.AUDAT AS CONTRACT_DATE,
	VBAK.VBELN AS CONTRACT_NO, -- DOC_NO
	VBAP.POSNR AS DOC_ITEM,
	VBAK.VGBEL AS REF_DOC,
	VBAK.AUART AS DOC_TYPE,
	VBAP.LGORT AS SLOC,
	VBAP.MATNR AS PRODUCT_CODE,
	VBAP.ARKTX AS PRODUCT_NAME,
	VBAK.KUNNR AS CUSTOMER_CODE,
	KNA1.NAME1 AS CUSTOMER_NAME,
	DELIVERY_ORDER.WBSTK AS GOOD_ISSUE_STATUS,
	T151T.KTEXT AS CUSTOMER_GROUP,
	VBAK.VTWEG AS CHANNEL_CODE,
	VBAK.VKGRP AS SALE_GROUP,
	VBAK.VKBUR AS SALE_OFFICE,
	VBKD.PLTYP AS PRICE_LIST, --Dot ban hang
	VBAP.NETWR AS ORDER_AMOUNT, --Doanh thu theo PLHDD
	VBAP.KWMENG AS ORDER_QTY, -- Số lượng trên PLHĐ
	SUM(DELIVERY_ORDER.LFIMG) AS DELIVER_QTY, -- Số lượng theo Lệnh xuất hàng
	SUM(CASE WHEN DELIVERY_ORDER.WBSTK NOT IN ('A','B') THEN DELIVERY_ORDER.LFIMG END) AS ACTUAL_DELIVER_QTY -- Số lượng giao nhận thực tê
FROM
	sri_sap.VBAK
	JOIN sri_sap.VBAP
		ON VBAK.VBELN = VBAP.VBELN
		AND VBAK.MANDT = VBAP.MANDT
	LEFT JOIN sri_sap.KNA1
		ON VBAK.MANDT = KNA1.MANDT
		AND VBAK.KUNNR = KNA1.KUNNR
	LEFT JOIN sri_sap.T151T
		ON KNA1.KTOKD = T151T.KDGRP
		AND T151T.SPRAS = 'E'
		-- AND KNA1.MANDT = T151T.MANDT
	LEFT JOIN (
		SELECT
			LIPS.VGBEL, LIPS.VGPOS, VBUK.WBSTK, SUM(LIPS.LFIMG) AS LFIMG
		FROM sri_sap.LIPS
		LEFT JOIN sri_sap.VBUK
			ON VBUK.VBELN = LIPS.VBELN
			AND VBUK.MANDT = LIPS.MANDT
		GROUP BY LIPS.VGBEL, LIPS.VGPOS, VBUK.WBSTK
	) DELIVERY_ORDER
		ON VBAP.VBELN = DELIVERY_ORDER.VGBEL
		AND VBAP.POSNR = DELIVERY_ORDER.VGPOS
	LEFT JOIN [sri_sap].[VBKD] --Sales Document: Business Data
		ON 1=1
		AND [VBAK].[MANDT] = [VBKD].[MANDT]
		AND [VBAK].[VBELN] = [VBKD].[VBELN]
GROUP BY
	VBAK.AUDAT,
	VBAK.VBELN,
	VBAP.POSNR,
	VBAK.VGBEL,
	VBAK.AUART,
	VBAP.LGORT,
	VBAP.MATNR,
	VBAP.ARKTX,
	VBAK.KUNNR,
	KNA1.NAME1,
	DELIVERY_ORDER.WBSTK,
	T151T.KTEXT,
	VBAK.VTWEG,
	VBAK.VKGRP,
	VBAK.VKBUR,
	VBKD.PLTYP,
	VBAP.NETWR,
	VBAP.KWMENG
),
raw AS (
	SELECT
		CONTRACT_DATE,
		CONTRACT_NO, -- DOC_NO
		DOC_ITEM,
		REF_DOC,
		DOC_TYPE,
		SLOC,
		PRODUCT_CODE,
		PRODUCT_NAME,
		CUSTOMER_CODE,
		CUSTOMER_NAME,
		GOOD_ISSUE_STATUS,
		CUSTOMER_GROUP,
		CHANNEL_CODE,
		SALE_GROUP,
		SALE_OFFICE,
		PRICE_LIST,
		ORDER_AMOUNT,
		ORDER_QTY, -- Số lượng trên PLHĐ
		DELIVER_QTY, -- Số lượng theo Lệnh xuất hàng
		ACTUAL_DELIVER_QTY, -- Số lượng giao nhận thực tê
		ORDER_QTY - ACTUAL_DELIVER_QTY AS REMAINING_QTY,-- Số lượng chưa nhận giao theo PLHĐ
		CASE WHEN SLOC = '1202' THEN ORDER_QTY - ACTUAL_DELIVER_QTY END AS WAREHOUSE_QTY, -- Tồn tại nhà máy
		CASE WHEN SLOC NOT IN ('1202','1299','1298') THEN ORDER_QTY - ACTUAL_DELIVER_QTY END AS RENT_WAREHOUSE_QTY,-- Tồn kho thuê/kho PVCFC
		CASE WHEN SLOC = '1299' THEN ORDER_QTY - ACTUAL_DELIVER_QTY END AS TRANSIT_QTY-- Đã nhận khỏi kho NM/Đang trên đường vận chuyển
	FROM
		_SDdata
)
SELECT
	r1.CONTRACT_DATE,
	r1.CONTRACT_NO,
	r1.DOC_TYPE,
	r1.PRODUCT_CODE,
	r1.PRODUCT_NAME,
	r1.CUSTOMER_CODE,
	r1.CUSTOMER_NAME,
	r1.CUSTOMER_GROUP,
	r1.CHANNEL_CODE,
	r1.SALE_GROUP,
	r1.SALE_OFFICE,
	r1.PRICE_LIST,
	r1.ORDER_AMOUNT as CONTRACT_AMT,
	r1.ORDER_QTY as CONTRACT_QTY,
	SUM(r2.ORDER_QTY) AS SO_QTY,
	SUM(r2.DELIVER_QTY) as DELIVER_QTY,
	SUM(r2.ACTUAL_DELIVER_QTY) as ACTUAL_DELIVER_QTY,
	SUM(r2.REMAINING_QTY) as REMAINING_QTY,
	SUM(r2.WAREHOUSE_QTY) as WAREHOUSE_QTY,
	SUM(r2.RENT_WAREHOUSE_QTY) as RENT_WAREHOUSE_QTY,
	SUM(r2.TRANSIT_QTY) as TRANSIT_QTY
FROM
	(SELECT * FROM raw WHERE DOC_TYPE LIKE 'ZQC%' OR DOC_TYPE LIKE 'YQC%') AS r1
	LEFT JOIN (SELECT * FROM raw WHERE NOT(DOC_TYPE LIKE 'ZQC%' OR DOC_TYPE LIKE 'YQC%' OR DOC_TYPE LIKE 'ZQT%' OR DOC_TYPE LIKE 'YQT%')) AS r2
	ON r1.CONTRACT_NO = r2.REF_DOC
		AND r1.DOC_ITEM = r2.DOC_ITEM
GROUP BY
	r1.CONTRACT_DATE,
	r1.CONTRACT_NO,
	r1.DOC_TYPE,
	r1.PRODUCT_CODE,
	r1.PRODUCT_NAME,
	r1.CUSTOMER_CODE,
	r1.CUSTOMER_NAME,
	r1.CUSTOMER_GROUP,
	r1.CHANNEL_CODE,
	r1.SALE_GROUP,
	r1.SALE_OFFICE,
	r1.PRICE_LIST,
	r1.ORDER_AMOUNT,
	r1.ORDER_QTY;
GO


