WITH raw AS (
SELECT
    VBRK.FKDAT AS BILLING_DATE/* Chi tieu (32)-  Billing Date /Ngày Hóa đơn GTGT/XK	*/
	,VBRK.VBELN AS BILLING_DOC /* Chi tieu (31)-  Billing Document /Số Hóa đơn GTGT/XK	*/
	,VBRP.POSNR AS BILLING_ITEM
	,VBRK.FKART AS BILLING_TYPE /*Billing Type*/
	,TVFKT.VTEXT AS BILLING_TYPE_NAME
	,VBRP.PLTYP_AUFT AS PRICE_LIST
	,T189T.PTEXT AS PRICE_LIST_NAME
    ,VBRK.KUNAG AS CUSTOMER_CODE /*Chi tieu (1) - Customer Number /Mã khách hàng*/
    ,KNA1.ADRNR AS CUSTOMER_ADDRESS_CODE
	,KNA1.XCPDK AS ONE_TIME_CUSTOMER_FLG
    ,VBRK.BUKRS AS COMPANY_CODE /*Chi tieu (3) - Company Code/ Mã công ty	  */
    ,VBRP.MATNR AS PRODUCT_CODE /*Chi tieu (4) - Material /Mã sản phẩm		  */
    ,VBRP.ARKTX AS PRODUCT_NAME /*Chi tieu (5) - Description /Tên sản phẩm	  */
	,VBRP.VKORG_AUFT AS SALE_ORG /* Chi tieu (21)-  Sales Organization /Mã Tổ chức bán hàng */
	,TVKOT.VTEXT AS SALE_ORG_NAME
    ,VBRP.VTWEG_AUFT AS CHANNEL_CODE /* Chi tieu (22)-  Distribution Channel  /Mã kênh BH		*/
	,TVTWT.VTEXT AS CHANNEL_NAME
    ,VBRP.VKBUR AS SALE_OFFICE/* Chi tieu (24)-  Sales Office /Mã Thị trường cấp 1     */
	,TVKBT.BEZEI AS SALE_OFFICE_NAME
    ,VBRP.VKGRP AS SALE_GROUP/* Chi tieu (26)-  Sales Group / Mã Thị trường cấp 2		*/
	,TVGRT.BEZEI AS SALE_GROUP_NAME
    ,VBRK.KDGRP AS CUSTOMER_GROUP_CODE/* Chi tieu (28)-  Customer Group /Mã nhóm khách hàng	*/
	,T151T.KTEXT AS CUSTOMER_GROUP_NAME
	,VBRK.WAERK AS DOC_CURRENCY /* Chi tieu (34)-  Currency /Loại tiền					*/
    ,VBRP.SPART AS DIVISION_CODE /* Chi tieu (37)-  Division /Ngành hàng					*/
	,TSPAT.VTEXT AS DIVISION_NAME
    ,VBRP.LGORT AS STORAGE_LOC/* Chi tieu (39)-  Sloc / Kho							*/
	,T001L.LGOBE AS STORAGE_LOC_NAME
	,VBPA.PERNR AS EMPLOYEE_CODE
	,CONCAT(PA0002.VORNA,' ',PA0002.NACHN) AS EMPLOYEE_NAME

    ,VBRP.VRKME AS UOM/*Chi tieu (6) -  UOM / Đơn vị tính*/
    ,CASE WHEN VBRK.FKART IN ('ZG3','ZG4','ZG2', 'ZL2') THEN 0 ELSE VBRP.FKLMG END AS BILLED_QTY /*Chi tieu (7) -  Billed Qty /Số lượng ra hóa đơn*/
    --,VBRP.MEINS AS BUOM    
    ,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRP.NETWR ELSE  VBRP.NETWR * 100 END) ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRP.NETWR ELSE  VBRP.NETWR * 100 END) END AS NET_VALUE /* Chi tieu (9) -  Net Value /Doanh thu     */
    ,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRP.MWSBP ELSE VBRP.MWSBP * 100 END) ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRP.MWSBP ELSE VBRP.MWSBP * 100 END) END AS TAX /* Chi tieu (10)-  Tax /Thuế GTGT		   */
    ,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRP.WAVWR ELSE VBRP.WAVWR * 100 END) ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRP.WAVWR ELSE VBRP.WAVWR * 100 END) END AS COGS/* Chi tieu (12)-  COGS / Giá vốn hàng bán   */
	
    -- 2023-10-02 QUANG - HANDLE IN MAIN QUERY
    -- ,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN (VBRP.NETWR - VBRP.WAVWR) * 100 ELSE (VBRP.NETWR - VBRP.WAVWR) * 100 END) ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN (VBRP.NETWR - VBRP.WAVWR) * 100 ELSE (VBRP.NETWR - VBRP.WAVWR) * 100 END)  END AS PROFIT
	-- ,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN (VBRP.NETWR + VBRP.MWSBP) * 100 ELSE (VBRP.NETWR + VBRP.MWSBP) * 100 END) ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN (VBRP.NETWR + VBRP.MWSBP) * 100 ELSE (VBRP.NETWR + VBRP.MWSBP) * 100 END) END AS TOTAL	
	
    ,KONV.KBETR / KONV.KPEIN AS UNIT_PRICE
	,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END) * VBRP.NETWR ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END) * VBRP.NETWR  END AS NET_VALUE_VND
	,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END) * VBRP.MWSBP ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END) * VBRP.MWSBP END AS TAX_VND
	,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END) * VBRP.WAVWR ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END) * VBRP.WAVWR END AS COGS_VND
	
    -- 2023-10-02 QUANG - HANDLE IN MAIN QUERY
    -- ,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END) * (VBRP.NETWR   - VBRP.WAVWR)  ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END) * (VBRP.NETWR   -  VBRP.WAVWR) END AS PROFIT_VND
    -- ,CASE WHEN VBRK.FKART IN ('ZRE1', 'ZRE2','YRE1','YRE2', 'ZG2', 'ZG3','ZG4','YG2','YG3', 'YG4') THEN -1 * (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END) * (VBRP.NETWR +  VBRP.MWSBP) ELSE (CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF * 1000 ELSE VBRK.KURRF * 100 END ) * (VBRP.NETWR + VBRP.MWSBP) END AS TOTAL_VND
    
    -- 2023-10-02 QUANG - UPDATE AS CORRECT FX
    --,VBRK.KURRF AS EXCHANGE_RATE_FI
    ,CASE WHEN VBRK.WAERK <> 'VND' THEN VBRK.KURRF*1000 ELSE VBRK.KURRF * 100 END AS EXCHANGE_RATE_FI
    --,VBRK.STWAE 

	,CASE WHEN VBRK.FKSTO <> '' OR VBRK.SFAKN <> '' THEN 'Canceled' ELSE 'Completed' END AS BILLING_STATUS
    ,VBRK.FKSTO AS CANCEL_STATUS/* Chi tieu (41)-  Cancel Status /TT hủy					*/
    ,VBRK.SFAKN AS CANCEL_BILLING/* Chi tieu (42)-  Cancelled billing /Số Billing gốc		*/   
    --,VBRP.FKIMG  /* chinhHN/11.7.2019 add.*/
    ,VBRP.TAXM1 AS TAX_CLASSIFICATION_MATERIAL
    ,VBRK.TAXK1 AS TAX_CLASSIFICATION_CUSTOMER
	,VBAK.VGBEL AS CONTRACT_NUMBER
	,VBRP.AUBEL AS SALE_ORDER_DOC/* Chi tieu (36)-  Sales Document /Số lệnh xuất hàng		*/
	,VBRP.AUPOS AS SALE_ORDER_ITEM
	,VBAK.BSTNK AS PO_NUMBER
	,TVAKT.AUART AS SALE_TYPE
	,TVAKT.BEZEI AS SALE_TYPE_NAME
	,VBRP.VGBEL AS DELIVERY_DOC
    ,VBRP.VGPOS AS DELIVERY_ITEM
	,CASE WHEN LIPS.WADAT_IST='00000000' THEN VBRK.FKDAT ELSE LIPS.WADAT_IST END AS ACTUAL_GI_DATE
	,VBRK.KNUMV AS CONDITION_CODE
	,KONV.KNUMH AS CONDITION_RECORD_NUM
    ,KONV.KPOSN AS CONDITION_ITEM
  FROM sri_sap.VBRK
  LEFT JOIN sri_sap.VBRP ON VBRK.VBELN = VBRP.VBELN
  LEFT JOIN sri_SAP.VBPA ON VBRP.VBELN = VBPA.VBELN AND VBPA.PARVW = 'VE'
  LEFT JOIN sri_sap.MARA ON MARA.MATNR = VBRP.MATNR
  LEFT JOIN (SELECT KONV.KNUMH,KONV.KNUMV, KONV.KPOSN, KONV.KBETR,KONV.KPEIN, KONV.KAWRT, SUM(KONV.KWERT) AS KWERT FROM sri_sap.KONV WHERE KONV.KINAK NOT IN ('X', 'M', 'W') /*Condition is inactive*/ AND KONV.KSCHL IN ('ZPR0', 'ZD01', 'ZPRT','ZR01') GROUP BY KONV.KNUMH,KONV.KNUMV, KONV.KPOSN, KONV.KBETR,KONV.KPEIN, KONV.KAWRT) AS KONV ON VBRK.KNUMV = KONV.KNUMV AND VBRP.POSNR = KONV.KPOSN
  LEFT JOIN sri_sap.KNA1 ON KNA1.KUNNR =VBRK.KUNAG
  LEFT JOIN sri_sap.TVKOT ON TVKOT.VKORG= VBRP.VKORG_AUFT AND TVKOT.SPRAS = 'E'
  LEFT JOIN sri_sap.TVTWT ON TVTWT.VTWEG = VBRP.VTWEG_AUFT AND TVTWT.SPRAS = 'E'
  LEFT JOIN sri_sap.TVKBT ON TVKBT.VKBUR = VBRP.VKBUR AND TVTWT.SPRAS = 'E'
  LEFT JOIN sri_sap.TVGRT ON TVGRT.VKGRP = VBRP.VKGRP AND TVGRT.SPRAS = 'E'
  LEFT JOIN sri_sap.T151T ON T151T.KDGRP = VBRK.KDGRP AND T151T.SPRAS = 'E'
  LEFT JOIN sri_sap.PA0002 ON VBPA.PERNR = PA0002.PERNR
  LEFT JOIN sri_sap.TSPAT ON VBRP.SPART = TSPAT.SPART AND TSPAT.SPRAS = 'E'
  LEFT JOIN (SELECT LGORT, LGOBE FROM sri_sap.T001L GROUP BY LGORT, LGOBE) AS T001L ON T001L.LGORT = VBRP.LGORT /*GROUP BY SLOC TABLE TO REMOVE PLANT CODE, need to check in sap SLOC 1280, 1285*/
  LEFT JOIN (SELECT LIPS.VBELN, LIPS.POSNR, LIKP.WADAT_IST FROM sri_sap.LIPS LEFT JOIN sri_sap.LIKP ON LIKP.VBELN = LIPS.VBELN) AS LIPS ON LIPS.VBELN = VBRP.VGBEL AND LIPS.POSNR = VBRP.VGPOS
  LEFT JOIN sri_sap.T189T ON VBRP.PLTYP_AUFT = T189T.PLTYP AND T189T.SPRAS = 'E'
  LEFT JOIN sri_sap.VBAK ON VBRP.AUBEL = VBAK.VBELN AND VBRP.MANDT = VBAK.MANDT
  LEFT JOIN sri_sap.TVAKT ON VBAK.MANDT = TVAKT.MANDT AND TVAKT.SPRAS = 'E' AND VBAK.AUART = TVAKT.AUART
  LEFT JOIN sri_sap.TVFKT ON VBAK.MANDT = TVFKT.MANDT AND TVFKT.SPRAS = 'E' AND VBRK.FKART = TVFKT.FKART
)
SELECT
    BILLING_DATE,
    BILLING_DOC, 
	BILLING_ITEM,
	BILLING_TYPE,
	BILLING_TYPE_NAME,
	PRICE_LIST,
	PRICE_LIST_NAME,
	CUSTOMER_CODE,
	CUSTOMER_ADDRESS_CODE,
	ONE_TIME_CUSTOMER_FLG,
	COMPANY_CODE,
	PRODUCT_CODE,
	PRODUCT_NAME,
	SALE_ORG,
	SALE_ORG_NAME,
	CHANNEL_CODE,
	CHANNEL_NAME,
	SALE_OFFICE,
	SALE_OFFICE_NAME,
	SALE_GROUP,
	SALE_GROUP_NAME,
	CUSTOMER_GROUP_CODE,
	CUSTOMER_GROUP_NAME,
	DOC_CURRENCY,
	DIVISION_CODE ,
	DIVISION_NAME,
	STORAGE_LOC,
	STORAGE_LOC_NAME,
	EMPLOYEE_CODE,
	EMPLOYEE_NAME,
	UOM,
	BILLED_QTY,
    NET_VALUE,
    TAX,
    COGS,
    NET_VALUE - COGS AS PROFIT,
    NET_VALUE + TAX AS TOTAL,
    UNIT_PRICE,
    ROUND(NET_VALUE_VND, 0) as NET_VALUE_VND,
    ROUND(TAX_VND,0) as TAX_VND,
    ROUND(COGS_VND,0) as COGS_VND,
    ROUND(NET_VALUE_VND,0) - ROUND(COGS_VND,0) AS PROFIT_VND,
    ROUND(NET_VALUE_VND,0) + ROUND(TAX_VND,0) AS TOTAL_VND,
    EXCHANGE_RATE_FI,
    --STWAE,
    BILLING_STATUS,
	CANCEL_STATUS,
	CANCEL_BILLING,
	TAX_CLASSIFICATION_MATERIAL,
	TAX_CLASSIFICATION_CUSTOMER,
	CONTRACT_NUMBER,
	SALE_ORDER_DOC,
	SALE_ORDER_ITEM,
	PO_NUMBER,
	SALE_TYPE,
	SALE_TYPE_NAME,
	DELIVERY_DOC,
	DELIVERY_ITEM,
	ACTUAL_GI_DATE,
	CONDITION_CODE,
	CONDITION_RECORD_NUM,
	CONDITION_ITEM
FROM raw